version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: mudlands-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
      - ./ollama/config:/config
      - ai-content:/data/ai-content
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_KEEP_ALIVE=5m
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 12G
        reservations:
          cpus: '2'
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mudlands-ai

  redis-ai:
    image: redis:7-alpine
    container_name: mudlands-redis-ai
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-ai-data:/data
    command: >
      redis-server
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
      --save 60 1
      --save 300 10
      --save 900 100
    networks:
      - mudlands-ai
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  ai-monitor:
    image: prom/node-exporter:latest
    container_name: mudlands-ai-monitor
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - ai-content:/data/ai-content:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - mudlands-ai

networks:
  mudlands-ai:
    driver: bridge
    name: mudlands-ai-network

volumes:
  ollama-models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ai-storage/models
  ai-content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ai-storage/content
  redis-ai-data:
    driver: local